[[plugins]]
  package = "@netlify/plugin-emails"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST"
